[package]
edition = "2021"
name = "ppaass-codec"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ppaass-protocol={git = "https://github.com/quhxuxm/ppaass-protocol.git", branch = "main"}
ppaass-crypto={git = "https://github.com/quhxuxm/ppaass-crypto.git", branch = "main"}
thiserror = "1.0"
bytes="1.5"
tokio-util={version="0.7", features = ["codec"]}
flate2="1.0"
log="0.4"
pretty-hex="0.4.0"
pin-project="1.1"
futures="0.3"
futures-util="0.3"
uuid={version="1.5", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"